version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"           # kör en gång i veckan
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    security-updates-only: true    # endast säkerhetsuppdateringar (mindre brus)
    open-pull-requests-limit: 2

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    security-updates-only: true
    open-pull-requests-limit: 2