version: 2
updates:
  # 1) Maven (applikationen) — säkerhet + patch/minor i samma regel (unikt combo)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"           # måndagar kl 01:00 UTC
      day: "monday"
      time: "01:00"
      timezone: "UTC"
    target-branch: "test"          # PRs går till arbetsbranchen; CI kör där först
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    groups:
      maven-security:              # samla säkerhetsuppdateringar
        applies-to: security-updates
        patterns: ["*"]
      maven-patch-minor:           # samla icke-säkerhet (patch/minor)
        update-types: ["patch", "minor"]
        patterns: ["*"]
    ignore:                        # stora hopp planeras separat
      - dependency-name: "org.springframework.boot:*"
        update-types: ["major"]

  # 2) GitHub Actions (CI) — ENDAST SÄKERHET
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"           # 15 min efter Maven
      day: "monday"
      time: "01:15"
      timezone: "UTC"
    security-updates-only: true
    target-branch: "test"
    open-pull-requests-limit: 3
    rebase-strategy: "auto"
    groups:
      gha-security:
        applies-to: security-updates
        patterns: ["*"]
