title = "Custom Gitleaks config"

# Global allowlist (gäller för hela repo:t)
[allowlist]
description = "Ignorera exempel-/testfiler och vanliga placeholders"

# Filer att ignorera (regex på filnamn/sökväg)
files = [
    ".env.example",                 # endast exempel, inga riktiga hemligheter
    ".*application-test\\.properties" # test-konfig (H2/JMS), inga secrets här
]

# Vanliga strängar som inte ska räknas som hemligheter
regexes = [
    '''(?i)changeme''',
    '''(?i)to-be-set''',
    '''(?i)example''',
    '''(?i)dummy'''
]
