title = "Custom Gitleaks config"

# Huvudnivå allowlist (map), inte lista [[allowlist]]
[allowlist]
description = "Ignorera exempel/test-konfigfiler och vanliga placeholders"

# Filer som ska ignoreras för att undvika falsklarm
files = [
    ".env.example",
    ".*application-test.properties"
]

# Vanliga strängar (placeholders) som inte ska räknas som hemligheter
regexes = [
    '''(?i)changeme''',
    '''(?i)to-be-set''',
    '''(?i)example''',
    '''(?i)dummy'''
]
