title = "Custom Gitleaks config"

# Ignorera exempel- och testfiler som kan trigga falsklarm
[[allowlist]]
description = "Ignore example env files and test configs"
files = [
    ".env.example",
    ".*application-test.properties"
]

# Ignorera vanliga placeholders
[[allowlist]]
description = "Ignore common placeholders"
regexes = [
    '''(?i)(changeme|to-be-set|example|dummy)'''
]
