version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: integration
      POSTGRES_PASSWORD: integration_pass
      POSTGRES_DB: integrationdb
      TZ: Europe/Stockholm  # Ställ in tidszon för OS
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - integration-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U integration -d integrationdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    environment:
      TZ: Europe/Stockholm  # Ställ in tidszon för OS
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - integration-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      timeout: 5s
      retries: 5

  integration-app:
    image: igor88gomes/spring-boot-integration:latest
    container_name: integration-app
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      TZ: Europe/Stockholm  # Ställ in tidszon för OS
    volumes:
      - ./logs:/app/logs     # Loggfiler delas mellan container och värd
    networks:
      - integration-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  integration-net:
