version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    # Läser variabler från .env för substitutions (Compose läser .env i projektroten).
    # Kräver lösenord: stoppar tidigt om DB_PASSWORD saknas.
    environment:
      POSTGRES_USER: ${DB_USER:-integration}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Set DB_PASSWORD in .env}   # <-- krävs
      POSTGRES_DB: ${DB_NAME:-integrationdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - integration-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U integration -d integrationdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    # Exponera endast webb-konsolen lokalt; applikationen når ActiveMQ-brokern via Docker-nätet (activemq:61616).
    ports:
      - "127.0.0.1:8161:8161"
    networks:
      - integration-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 10s
      timeout: 5s
      retries: 5

  integration-app:
    image: igor88gomes/spring-boot-integration:latest
    container_name: integration-app
    # Läser DB_* och BROKER_* från .env in i containern (krävs av Spring)
    env_file:
      - .env                               # <-- lägg .env i projektroten
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy
    ports:
      - "8080:8080"
    # Kör 100% som icke-root (säkerhet)
    user: "10001:10001"
    volumes:
      # Logik ändrad: appen skriver till en NAMNGIVEN VOLYM (alltid skrivbar för icke-root).
      # En separat sidecar (nedan) exporterar automatiskt till ./logs på värden.
      - app_logs:/app/logs
    networks:
      - integration-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sidecar: exporterar loggar från volymen till ./logs på värden — utan root, inga extra steg.
  log-exporter:
    image: alpine:3.20
    container_name: log-exporter
    # Kör som icke-root (1000:1000 matchar den vanligaste användaren på värden)
    user: "1000:1000"
    depends_on:
      integration-app:
        condition: service_started
    volumes:
      - app_logs:/in:ro    # läs från appens volym (read-only)
      - ./logs:/out        # skriv till repo-mappen på värden
      # Om någon kör SELinux enforcing och behöver label: använd ./logs:/out:Z
    command:
      - /bin/sh
      - -lc
      - |
        mkdir -p /out
        # Enkel och portabel kontinuerlig kopiering
        while true; do
          cp -r /in/. /out/ 2>/dev/null || true
          sleep 2
        done
    networks:
      - integration-net
    restart: unless-stopped

volumes:
  postgres_data:
  app_logs:

networks:
  integration-net:
