# .github/workflows/ci.yaml
name: Java CI with Maven

on:
  push:
    branches: [ main, test ]    # Kör tester när man pushar till både main och test
  pull_request:
    branches: [ main ]          # Blockerar merge till main om CI inte är grön

concurrency:
  group: ci-${{ github.ref }}   # Avbryt äldre körningar på samma gren
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & test (JaCoCo)
        run: mvn -B clean verify

      # Ladda upp kodtäckningsrapport (även om tester fallerar, för analys)
      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 14

      # Skapa Javadoc ENDAST på main (inte i PR)
      - name: Generate Javadoc (main only)
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: mvn -B -DskipTests javadoc:javadoc

      - name: Upload Javadoc (main only)
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site/apidocs/
          retention-days: 14
