# .github/workflows/ci.yaml
name: Java CI with Maven

on:
  push:
    branches: [ main, test ]    # Kör tester när man pushar till både main och test
  pull_request:
    branches: [ main ]          # Blockerar merge till main om CI inte är grön

concurrency:
  group: ci-${{ github.ref }}   # Avbryt äldre körningar på samma gren
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & test (JaCoCo)
        run: mvn -B clean verify

      # Kontroll: JaCoCo-rapport finns och är läsbar (HTML)
      - name: Kontrollera JaCoCo (HTML)
        id: jacoco_check
        if: always()
        run: |
          set -euo pipefail
          FILE="target/site/jacoco/index.html"
          if [ -s "$FILE" ] && grep -qi "jacoco" "$FILE"; then
            echo "has=true" >> "$GITHUB_OUTPUT"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
          fi

      # Ladda upp JaCoCo-rapport (14 dagar) – endast om giltig
      - name: Ladda upp JaCoCo-rapport (14 dagar)
        if: always() && steps.jacoco_check.outputs.has == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/**
          retention-days: 14

      # Logg om upload hoppas över
      - name: Hoppa över upload (JaCoCo saknas/ogiltig)
        if: always() && steps.jacoco_check.outputs.has != 'true'
        run: echo "JaCoCo saknas/ogiltig; hoppar över upload."

      # Kontroll: JavaDoc (endast på main) – index.html finns och är icke-tom
      - name: Kontrollera JavaDoc (endast main)
        id: javadoc_check
        if: always() && github.ref == 'refs/heads/main'
        run: |
          set -euo pipefail
          FILE="target/site/apidocs/index.html"
          if [ -s "$FILE" ]; then
            echo "has=true" >> "$GITHUB_OUTPUT"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
          fi

      # Ladda upp JavaDoc (14 dagar) – endast om giltig och på main
      - name: Ladda upp JavaDoc (14 dagar)
        if: always() && github.ref == 'refs/heads/main' && steps.javadoc_check.outputs.has == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site/apidocs/**
          retention-days: 14

      # Logg om upload hoppas över (JavaDoc)
      - name: Hoppa över upload (JavaDoc saknas/ogiltig)
        if: always() && github.ref == 'refs/heads/main' && steps.javadoc_check.outputs.has != 'true'
        run: echo "JavaDoc saknas/ogiltig; hoppar över upload."

