# .github/workflows/ci.yaml

name: Java CI with Maven and Docker

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: integration
          POSTGRES_PASSWORD: integration_pass
          POSTGRES_DB: integrationdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U integration -d integrationdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      activemq:
        image: rmohr/activemq:5.15.9
        ports:
          - 61616:61616
          - 8161:8161
        options: >-
          --health-cmd="curl -f http://localhost:8161 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for PostgreSQL..."
          until pg_isready -h localhost -U integration -d integrationdb; do sleep 2; done

          echo "Waiting for ActiveMQ..."
          until curl -sf http://localhost:8161; do sleep 2; done

      - name: Build with Maven (test profile + JaCoCo)
        run: mvn -B -Dspring.profiles.active=test clean install

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          retention-days: 14
