# .github/workflows/ci.yaml
name: Java CI with Maven

on:
  push:
    branches: [ main, test ]    # Kör tester när man pushar till både main och test
  pull_request:
    branches: [ main ]          # Blockerar merge till main om CI inte är grön

concurrency:
  group: ci-${{ github.ref }}   # Avbryt äldre körningar på samma gren
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # För att committa SVG-badgen

    steps:
      - uses: actions/checkout@v4

      # Checkout av källkod (med historik)
      # Viktigt: fetch-depth: 0 krävs för att läsa commit-intervallet (before..sha).
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Sätt flagga för JavaDoc
      # Endast på push → main och om NÅGON commit i pushen innehåller "[javadoc]".
      - name: Set JavaDoc flag
        id: jdoc
        shell: bash
        run: |
          set -euo pipefail
          JDOC=false
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            if git log --pretty=%B "${{ github.event.before }}..${{ github.sha }}" | grep -Fq "[javadoc]"; then
              JDOC=true
            fi
          fi
          echo "enabled=$JDOC" >> "$GITHUB_OUTPUT"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & test (JaCoCo)
        run: mvn -B clean verify

      # Kodtäckningsbadge (generera SVG från jacoco.csv) ===
      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: .github/badges
          generate-branches-badge: false

      # Commit av badge på test (så följer den med i PR → main)
      - name: Commit coverage badge (på test)
        if: github.ref == 'refs/heads/test'
        uses: EndBug/add-and-commit@v9
        with:
          add: ".github/badges/*.svg"
          message: "chore(ci): update coverage badge (test)"
          default_author: github_actions

      # Kontroll: JaCoCo-rapport finns och är läsbar (HTML)
      - name: Kontrollera JaCoCo (HTML)
        id: jacoco_check
        if: always()
        run: |
          set -euo pipefail
          FILE="target/site/jacoco/index.html"
          if [ -s "$FILE" ] && grep -qi "jacoco" "$FILE"; then
            echo "has=true" >> "$GITHUB_OUTPUT"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
          fi

      # Ladda upp JaCoCo-rapport (14 dagar) – endast om giltig
      - name: Ladda upp JaCoCo-rapport (14 dagar)
        if: always() && steps.jacoco_check.outputs.has == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/**
          retention-days: 14

      # Logg om upload hoppas över
      - name: Hoppa över upload (JaCoCo saknas/ogiltig)
        if: always() && steps.jacoco_check.outputs.has != 'true'
        run: echo "JaCoCo saknas/ogiltig; hoppar över upload."

      # Genererar JavaDoc med Maven (skippar tester)
      - name: Generera JavaDocs
        if: steps.jdoc.outputs.enabled == 'true'
        run: mvn -B -DskipTests javadoc:javadoc

      # Kontrollerar att mappen med JavaDoc faktiskt skapades och inte är tom
      - name: Kontrollera JavaDocs
        id: javadoc_check
        if: steps.jdoc.outputs.enabled == 'true'
        run: |
          if [ -d target/site/apidocs ] && [ "$(ls -A target/site/apidocs)" ]; then
            echo "has=true" >> "$GITHUB_OUTPUT"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
          fi

      # Ladda upp JavaDoc som artefakt om den finns
      - name: Ladda upp JavaDocs (14 dagar)
        if: steps.jdoc.outputs.enabled == 'true' && steps.javadoc_check.outputs.has == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: javadocs
          path: target/site/apidocs/**
          retention-days: 14

      # Logg vid hopp (endast när flaggan var sann)
      - name: Hoppa över upload (JavaDocs saknas)
        if: steps.jdoc.outputs.enabled == 'true' && steps.javadoc_check.outputs.has != 'true'
        run: echo "JavaDocs saknas/ogiltiga; hoppar över upload."

      # Spring Cloud Contract: publicera stubs.jar som artifact (endast main)
      # Kontroll: finns och är icke-tom?
      - name: Kontrollera stubs (SCC)
        id: stubs_check
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          set -euo pipefail
          FILE=$(ls -1 target/*-stubs.jar 2>/dev/null | head -n1 || true)
          if [ -n "${FILE:-}" ] && [ -s "$FILE" ]; then
            echo "has=true" >> "$GITHUB_OUTPUT"
            echo "path=$FILE" >> "$GITHUB_OUTPUT"
            echo "Hittade stubs: $FILE"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
            echo "Inga stubs hittades i target/*-stubs.jar"
          fi

      - name: Ladda upp stubs (14 dagar)
        if: github.ref == 'refs/heads/main' && steps.stubs_check.outputs.has == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: stubs
          path: ${{ steps.stubs_check.outputs.path }}
          retention-days: 14

      - name: Hoppa över upload (stubs saknas/ogiltig)
        if: github.ref == 'refs/heads/main' && steps.stubs_check.outputs.has != 'true'
        run: echo "stubs saknas/ogiltig; hoppar över upload."

      # Felsökning: ladda upp testrapporter om bygget faller
      - name: Ladda upp Surefire-rapporter (endast vid fel)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            target/surefire-reports/**
            target/failsafe-reports/**
            **/*-jvmRun*.dump
            **/*.dumpstream
          retention-days: 14
          if-no-files-found: ignore