name: Secret Scan

on:
  push:
    branches: [ "main", "test", "**feature/**" ]
    paths-ignore:
      - "**/*.md"    # ignorera markdown
      - "docs/**"    # ignorera dokumentation
  pull_request:
  schedule:
    - cron: "0 3 * * 1"   # måndag 03:00 UTC (veckovis säkerhetsnät)
  workflow_dispatch:       # manuell körning

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # skanna hela git-historiken

      - name: Gitleaks (enforce, fail on findings)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--config=.gitleaks.toml --redact --no-banner --exit-code 1"
