name: Secret Scan

on:
  push:
    branches: [ "main", "test", "**feature/**" ]
    paths-ignore:
      - "**/*.md"    # ignorera markdown
      - "docs/**"    # ignorera dokumentation
  pull_request:
  schedule:
    - cron: "0 3 * * 1"   # måndag 03:00 UTC
  workflow_dispatch:       # manuell körning

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write   # behövs om du laddar upp SARIF
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # behövs för att skanna hela historiken
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--config=.gitleaks.toml --report-format sarif --report-path gitleaks.sarif"
      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gitleaks.sarif
