name: Secret Scan

on:
  push:
    branches: [ "main", "test", "**feature/**" ]
    paths-ignore:
      - "**/*.md"    # ignorera markdown
      - "docs/**"    # ignorera dokumentation
  pull_request:
  schedule:
    - cron: "0 3 * * 1"   # måndag 03:00 UTC (veckovis säkerhetsnät)
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # skanna hela git-historiken

      # Kör Gitleaks med default-argument; den hittar .gitleaks.toml automatiskt
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
