name: Secret Scan

on:
  push:
    branches: [ "main", "test" ]
    paths-ignore: [ "**/*.md", "docs/**" ]    # ignorera Markdown och dokumentation
  pull_request:
    branches: [ "main" ]                      # PR:er mot main
  schedule:
    - cron: "0 3 * * 1"                       # veckovis skyddsnät (måndagar 03:00 UTC)
  workflow_dispatch:

concurrency:
  group: secret-scan-${{ github.ref }}        # undvik parallella körningar per gren
  cancel-in-progress: true

jobs:
  gitleaks:                                    # check-namn (visas i PR)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }               # krävs för fullständig skanning (git-historik)

      # PR: snabb skanning — blockerar merge om hemlighet hittas
      - name: Gitleaks (PR - fast)
        if: github.event_name == 'pull_request'
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --no-git --redact --verbose --config-path=.gitleaks.toml
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }

      # push/schedule: fullständig skanning — genomsöker hela historiken
      - name: Gitleaks (push/schedule - full)
        if: github.event_name != 'pull_request'
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --redact --verbose --config-path=.gitleaks.toml
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
